### ISSUE TITLE
Message Events causes startup failure with ProcessParsingValidationException

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1907]
### Describe the bug

Consider process:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1994838/150218437-4b6c73f9-a62d-43f2-80db-e26cf23afde4.png">

deps:

```xml
 <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-quarkus</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-process-management</artifactId>
    </dependency>
```

The events dep is not included.

generated xml:

```
...
  <bpmn2:itemDefinition id="MyMessageType" structureRef=""/>
  <bpmn2:message id="_Tb0loFueEDqodfXxgLbkbQ" itemRef="MyMessageType" name="MyMessage"/>
...
    <bpmn2:intermediateCatchEvent id="_7EB68ACF-33FE-4BB4-88DB-BF91E0385AA7" name="Some Event">
      <bpmn2:extensionElements>
        <drools:metaData name="elementname">
          <drools:metaValue><![CDATA[Some Event]]></drools:metaValue>
        </drools:metaData>
      </bpmn2:extensionElements>
      <bpmn2:incoming>_C2E5A711-2F42-46FC-B080-BACF81EC2906</bpmn2:incoming>
      <bpmn2:outgoing>_9EDDABB5-2FDB-4A3F-94EC-48176D91BA17</bpmn2:outgoing>
      <bpmn2:messageEventDefinition drools:msgref="MyMessage" messageRef="_Tb0loFueEDqodfXxgLbkbQ"/>
    </bpmn2:intermediateCatchEvent>
...

```

a Message start event  generates the error:

` - Could not find message _Q7m2MFufEDqWk8eNDaFjCw`

### Expected behavior

I would expect the deployment to work. but seems the codegen is failing.

### Actual behavior

Validation error: ` - Node id = "", name = "" is malformed: Could not find message "_Tb0loFueEDqodfXxgLbkbQ"`

### How to Reproduce?

see image.

**Comment by fjtirado** [comment]
I think we need a reproducer. A link to a github repo for the example you are using that cause the failure

**Comment by StephenOTT** [comment]
[inter-event.bpmn.txt](https://github.com/kiegroup/kogito-runtimes/files/7905217/inter-event.bpmn.txt)

Created with vs-code kogito tools extension

**Comment by StephenOTT** [comment]
Error:

```
Caused by: org.jbpm.bpmn2.xml.MalformedNodeException: Node id = "", name = "" is malformed: Could not find message "_2_-vUFwaEDqU7ppiO__EDw"

	at org.jbpm.bpmn2.xml.IntermediateCatchEventHandler.handleMessageNode(IntermediateCatchEventHandler.java:249)
	at org.jbpm.bpmn2.xml.IntermediateCatchEventHandler.end(IntermediateCatchEventHandler.java:89)
	at org.drools.core.xml.ExtensibleXmlParser.endElement(ExtensibleXmlParser.java:441)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:948)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2899)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.drools.core.xml.ExtensibleXmlParser.read(ExtensibleXmlParser.java:318)
	at org.drools.core.xml.ExtensibleXmlParser.read(ExtensibleXmlParser.java:181)
	at org.jbpm.compiler.xml.XmlProcessReader.read(XmlProcessReader.java:91)
	at org.kie.kogito.codegen.process.ProcessCodegen.parseProcessFile(ProcessCodegen.java:264)
	at org.kie.kogito.codegen.process.ProcessCodegen.lambda$ofCollectedResources$2(ProcessCodegen.java:127)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources(ProcessCodegen.java:148)
	... 25 more
```

**Comment by StephenOTT** [comment]
@fjtirado were you able to re-create or do you want a proj?  This was in 1.15.  I will also re-test on 1.16.

**Comment by StephenOTT** [comment]
Project files for a failing startup: https://github.com/StephenOTT/broken-message-kogito-example

**Comment by StephenOTT** [comment]
Jira ticket created: https://issues.redhat.com/browse/KOGITO-6638

**Comment by StephenOTT** [comment]
same issue occurs with Message Start Events in 1.16.1

**Comment by fjtirado** [comment]
Catch Message without output asociation (and without an event adddon in the dependencies) are not going to be succesfully deployed in Kogito, but I used your JIRA to create a PR https://github.com/kiegroup/kogito-runtimes/pull/2009 to improve the error message you are getting.

**Comment by elguardian** [comment]
follow up work in here https://github.com/kiegroup/kie-issues/issues/432
