### ISSUE TITLE
KnowledgeBuilderConfigurationImpl cannot be cast to SemanticKnowledgeBuilderConfigurationImpl

### ISSUE THREAD

**Issue by DawnandGloaming** [kiegroup/kogito-runtimes#2874]
### Describe the bug

java.lang.ClassCastException: class org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl cannot be cast to class org.jbpm.compiler.xml.compiler.SemanticKnowledgeBuilderConfigurationImpl (org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl and org.jbpm.compiler.xml.compiler.SemanticKnowledgeBuilderConfigurationImpl are in unnamed module of loader 'app')
	at org.jbpm.compiler.ProcessBuilderImpl.configurePackageBuilder(ProcessBuilderImpl.java:101)
	at org.jbpm.compiler.ProcessBuilderImpl.<init>(ProcessBuilderImpl.java:97)
	at org.jbpm.process.builder.ProcessBuilderFactoryServiceImpl.newProcessBuilder(ProcessBuilderFactoryServiceImpl.java:26)
	at org.jbpm.process.builder.ProcessBuilderFactoryServiceImpl.newProcessBuilder(ProcessBuilderFactoryServiceImpl.java:23)
	at org.drools.compiler.compiler.ProcessBuilderFactory.newProcessBuilder(ProcessBuilderFactory.java:30)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.<init>(KnowledgeBuilderImpl.java:238)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.<init>(KnowledgeBuilderImpl.java:147)
	at org.drools.compiler.builder.impl.KnowledgeBuilderFactoryServiceImpl.newKnowledgeBuilder(KnowledgeBuilderFactoryServiceImpl.java:52)
	at org.kie.internal.builder.KnowledgeBuilderFactory.newKnowledgeBuilder(KnowledgeBuilderFactory.java:52)
	at com.rule.erule.core.engine.init.ERuleSessionAware.generateKbase(ERuleSessionAware.java:263)
	at com.rule.erule.core.engine.init.ERuleSessionAware.getRuleSetKbase(ERuleSessionAware.java:236)
	at com.rule.erule.core.engine.init.ERuleSessionAware.refreshRuleSet(ERuleSessionAware.java:496)
	at com.rule.erule.core.engine.task.RulesetCheckTask.run(RulesetCheckTask.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

My code is below:
    KnowledgeBuilder kbuilder = null;
    InternalKnowledgeBase kbase = null;
    kbuilder = KnowledgeBuilderFactory.newKnowledgeBuilder();

**Comment by gitgabrio** [comment]
Hi @DawnandGloaming I'm not expert Process, but IMO  you are mixing two different "kind of" jars/inheritance tree. @mariofusco ?

**Comment by gitgabrio** [comment]
Hi @DawnandGloaming I'm not expert Process, but IMO  you are mixing two different "kind of" jars/inheritance tree. @mariofusco ?
